version: "2"
services:
  ts3:
    build: "."
    restart: "unless-stopped"
    ports:
      - "9987:9987/udp"
      - "30033:30033"
      - "10011:10011"
    volumes:
      - "ts3_data:/home/ts3/data"
      
volumes:
  ts3_data: {}
    
